### ISSUE TITLE
Vote already in progress, but it's not...

### ISSUE THREAD

**Issue by Freekers** [ph03n1x9000/Codvote-B3-plugin#1]
I have this plugin setup and running on my Big Brother Bot version 1.10.8 in combination with COD4, but it keeps telling me 'Vote already in progress' while there really isn't... I can't seem to figure out why it thinks that there's already a vote in progress. What am I doing wrong?

Here is my logfile with the loglevel set to 8 after a fresh restart of B3: http://pastebin.com/rC8QuwJD

Many thanks!

**Comment by ph03n1x9000** [comment]
Error fixed, Please re-download and install. 
Thank you for feedback!

**Comment by Freekers** [comment]
Works! Thanks for the quick fix :+1:

**Comment by guillermosanero** [comment]
Hello, how are you? excuse my English I am from a translator ... 

I'm trying to make the plugin work in my mw3 server, will it be possible?? I loaded the maps etc, but I don't get an answer when inserting some command, only the "veto" command works for me
Could you help me to make it work? b3 recognizes it, but in the game you don't ...
